spring:
  application:
    name: ${SPRING_APPLICATION_NAME:kraheja-service}
  profiles.active: mumbaitest
  mvc:
    pathmatch:
        matching-strategy: ant_path_matcher
    hikari: 
     minimum-idle: ${hikari_minimum_idle:2}
     maximum-pool-size: ${hikari_maximum_pool_size:10}
     idle-timeout: 30000
     pool-name: KrahejaServicePool
     max-lifetime: 1000000
     auto-commit: false
     connection-timeout: 30000
     connection-test-query: SELECT 1 FROM DUAL
     connectionInitSql: ALTER SESSION SET NLS_DATE_FORMAT='DD-MM-RR'     
     
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none
    #database-platform: org.hibernate.dialect.Oracle12cDialect
    properties:
      hibernate:
        show_sql: true
        sql: DEBUG
        proc:
          param_null_passing: true
          spring:
#DO NOT CHANGE DDL-AUTO SETTING

---
feign:
  client:
    config:
      ${feign.client.crystal-report-service-name}:
        errorDecoder: kraheja.feign.confg.FeignErrorDecoder
        connectTimeout: 1800000
        readTimeout: 1800000
  
---
server:
 servlet:
  session:
   timeout: 60m
        
password:
  expiry: 10
  
permitted:
#  filters: /register,/h2-console/**,/report/**,/swagger-ui/**,/passwd/**,/certificate/**,/payroll/**,/test/**,/infra/**,/outinfra/**,/outgoing/**,/outrate/**
  filters: "/**"
  resources: /images/**,/js/**,/webjars/**,/index,html,/report/**,/v2/api-docs,/configuration/ui,/swagger-resources/**,/configuration/security,/swagger-ui.html,/building/**, /project/**,/purchase-bills/**,inspolendorsement/**,/admexph/**,/party/**,/inspolicy/**,/payroll/**,/test/**,/payrollreports/**,/infra/**,/outinfra/**,/outgoing/**,/outrate/**
  
cors:
  allowed:
    domains: http://localhost:4200/,http://192.168.55.108:4200/,http://192.168.55.13:4200/,http://192.168.55.124:4200/,http://localhost:4201/,http://192.168.55.108:4201/,http://192.168.55.13:4201/,http://192.168.55.124:4201/
    
swagger2:
  base.package: kraheja
  api:
    title: KRAHEJA
    description: KRAHEJA ERP 2.0
  contact:
    name: KRAHEJA
    url:
    email:
#logging:
# level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type: TRACE

---
spring:
  config:
    activate:
        on-profile: mumbaitest
    import: classpath:application-mumbaitest.yml
    
---
spring:
  config:
    activate:
        on-profile: mumbaiprod
    import: classpath:application-mumbaiprod.yml
    
---
spring:
  config:
    activate:
        on-profile: purengtest
    import: classpath:application-purengtest.yml
    
---
spring:
  config:
    activate:
        on-profile: pureng
    import: classpath:application-pureng.yml
