package kraheja.payroll.repository;

import java.util.List;
import java.util.Set;

import javax.persistence.Tuple;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import kraheja.payroll.bean.response.CalculateSalaryForTheseEmployees;
import kraheja.payroll.bean.response.GetInputScreenBean;
import kraheja.payroll.entity.Emppaymonth;
import kraheja.payroll.entity.EmppaymonthCK;

@Repository
public interface SalaryComputationRepository extends JpaRepository<Emppaymonth, EmppaymonthCK> {

	@Query("SELECT new kraheja.payroll.bean.response.CalculateSalaryForTheseEmployees(c.ejinCompany                       AS company,\r\n"
			+ "       c.ejinDepartment                    AS department,\r\n"
			+ "       c.ejinEmptype                       AS employeeType,\r\n"
			+ "       c.empjobinfoCK.ejinEmpcode                       AS empcode,\r\n"
			+ "       c.ejinPaymode                       AS paymode,\r\n"
			+ "       a.eperFullname                      AS empFullName,\r\n" + "       (SELECT entName\r\n"
			+ "        FROM   DbEntity\r\n" + "        WHERE  entityCk.entClass = 'ETYPE'\r\n"
			+ "               AND entityCk.entId <> '00000'\r\n"
			+ "               AND c.ejinEmptype = entityCk.entId) AS EmptypeName, \r\n"
			+ "       m.emppaymonthCK.empmPaymonth		AS paymonth )\r\n"
			+ "FROM   Emppersonal a,\r\n"
			+ "       Emppaymonth m,\r\n" + "       Empjobinfo c\r\n"
			+ "WHERE  a.emppersonalCK.eperEmpcode = c.empjobinfoCK.ejinEmpcode\r\n"
			+ "       AND a.emppersonalCK.eperEmpcode = m.emppaymonthCK.empmEmpcode\r\n"
			+ "       AND trim(c.ejinCompany) = :coy\r\n"
			+ "       AND trim(m.emppaymonthCK.empmPaymonth) = :paymonth\r\n"
			+ "       AND trim(m.emppaymonthCK.empmSalarytype) = :saltype\r\n"
			+ "       AND a.eperEffectiveupto IN (SELECT MAX(c.eperEffectiveupto)\r\n"
			+ "                                  FROM   Emppersonal c\r\n"
			+ "                                  WHERE  c.emppersonalCK.eperEmpcode = a.emppersonalCK.eperEmpcode)\r\n"
			+ "       AND c.ejinEffectiveupto IN (SELECT MAX(d.ejinEffectiveupto)\r\n"
			+ "                                  FROM   Empjobinfo d\r\n"
			+ "                                  WHERE  d.empjobinfoCK.ejinEmpcode = c.empjobinfoCK.ejinEmpcode)\r\n"
			+ "       AND m.empmPaystatus <> 'H'\r\n" + "       AND ( 'ALL' IN ( :empcode )\r\n"
			+ "              OR trim(c.empjobinfoCK.ejinEmpcode) IN ( :empcode ) )\r\n"
			+ "       AND ( 'ALL' IN ( :emptype )\r\n" + "              OR trim(c.ejinEmptype) IN ( :emptype ) )\r\n"
			+ "ORDER  BY c.ejinCompany,\r\n" + "          c.ejinDepartment,\r\n" + "          c.ejinEmptype,\r\n"
			+ "          c.empjobinfoCK.ejinEmpcode,\r\n" + "          c.ejinPaymode ")
	List<CalculateSalaryForTheseEmployees> findByComputeEmployee(String coy, String paymonth, String saltype,
			String empcode, String emptype);

	@Query(value = "select \r\n" + "	Empcode,\r\n" + "	Earndedcode,\r\n" + "	Earndedtype,\r\n"
			+ "	Computeno,\r\n" + "	Computetype,\r\n" + "	Schemeyn,\r\n" + "	Loanyn,\r\n" + "	Defaultsaltype,\r\n"
			+ "	Earndedrate,\r\n" + "	Paycycle,\r\n" + "	Ratecycle,\r\n" + "	Schemeapplyn\r\n" + "from (\r\n"
			+ "SELECT ESPK_EMPCODE as Empcode,\r\n" + "       ESPK_EARNDEDCODE as Earndedcode,\r\n"
			+ "       EDHM_EARNDEDTYPE as Earndedtype,\r\n" + "       EDHM_COMPUTENO as Computeno,\r\n"
			+ "       EDHM_COMPUTETYPE as Computetype,\r\n" + "       EDHM_SCHEMEYN as Schemeyn,\r\n"
			+ "       EDHM_LOANYN as Loanyn,\r\n" + "       EDHM_DEFAULTSALTYPE as Defaultsaltype,\r\n"
			+ "       ESPK_EARNDEDRATE as Earndedrate,\r\n" + "       ESPK_PAYCYCLE as Paycycle,\r\n"
			+ "       ESPK_RATECYCLE as Ratecycle,\r\n" + "       'Y' AS Schemeapplyn\r\n" + "FROM   EARNDEDMASTER,\r\n"
			+ "       EMPSALARYPACKAGE\r\n" + "WHERE  Rtrim(ESPK_EARNDEDCODE) = Rtrim(EDHM_EARNDEDCODE)\r\n"
			+ "       AND EDHM_LOANYN = 'N'\r\n" + "       AND EDHM_SCHEMEYN = 'N'\r\n"
			+ "       AND EDHM_COMPUTETYPE = 'R'\r\n" + "       AND EDHM_EARNDEDTYPE IN ( 'A', 'D' )\r\n"
			+ "       AND trim(ESPK_EMPCODE) = :empcode\r\n"
			+ "       AND :paymonth BETWEEN To_char(ESPK_EFFECTIVEFROM, 'YYYYMM') AND To_char(ESPK_EFFECTIVEUPTO, 'YYYYMM')\r\n"
			+ "UNION\r\n" + "SELECT :empcode as Empcode,\r\n" + "       CSPK_EARNDEDCODE as Earndedcode,\r\n"
			+ "       EDHM_EARNDEDTYPE as Earndedtype,\r\n" + "       EDHM_COMPUTENO as Computeno,\r\n"
			+ "       EDHM_COMPUTETYPE as Computetype,\r\n" + "       EDHM_SCHEMEYN as Schemeyn,\r\n"
			+ "       EDHM_LOANYN as Loanyn,\r\n" + "       EDHM_DEFAULTSALTYPE as Defaultsaltype,\r\n"
			+ "       0 as Earndedrate,\r\n" + "       CSPK_PAYCYCLE as Paycycle,\r\n"
			+ "       CSPK_RATECYCLE as Ratecycle,\r\n" + "       'Y' AS Schemeapplyn\r\n" + "FROM   EARNDEDMASTER,\r\n"
			+ "       COYSALARYPACKAGE\r\n" + "WHERE  Rtrim(CSPK_EARNDEDCODE) = Rtrim(EDHM_EARNDEDCODE)\r\n"
			+ "       AND EDHM_LOANYN = 'N'\r\n" + "       AND EDHM_SCHEMEYN = 'N'\r\n"
			+ "       AND EDHM_COMPUTETYPE = 'S'\r\n" + "       AND trim(CSPK_COY) = :coy\r\n"
			+ "       AND :paymonth BETWEEN To_char(CSPK_EFFECTIVEFROM, 'YYYYMM') AND To_char(CSPK_EFFECTIVEUPTO, 'YYYYMM')\r\n"
			+ "UNION\r\n" + "SELECT ESCH_EMPCODE as Empcode,\r\n" + "       CSPK_EARNDEDCODE as Earndedcode,\r\n"
			+ "       EDHM_EARNDEDTYPE as Earndedtype,\r\n" + "       EDHM_COMPUTENO as Computeno,\r\n"
			+ "       EDHM_COMPUTETYPE as Computetype,\r\n" + "       EDHM_SCHEMEYN as Schemeyn,\r\n"
			+ "       EDHM_LOANYN as Loanyn,\r\n" + "       EDHM_DEFAULTSALTYPE as Defaultsaltype,\r\n"
			+ "       ESCH_SCHEMEAMOUNT as Earndedrate,\r\n" + "       CSPK_PAYCYCLE as Paycycle,\r\n"
			+ "       CSPK_RATECYCLE as Ratecycle,\r\n" + "       ESCH_APPLICABLEYN AS Schemeapplyn\r\n"
			+ "FROM   EARNDEDMASTER,\r\n" + "       COYSALARYPACKAGE,\r\n" + "       EMPSCHEMEINFO\r\n"
			+ "WHERE  Rtrim(CSPK_EARNDEDCODE) = Rtrim(EDHM_EARNDEDCODE)\r\n"
			+ "       AND Rtrim(CSPK_EARNDEDCODE) = Rtrim(ESCH_SCHEMECODE)\r\n" + "       AND EDHM_LOANYN = 'N'\r\n"
			+ "       AND EDHM_SCHEMEYN = 'Y'\r\n" + "       AND EDHM_COMPUTETYPE = 'S'\r\n"
			+ "       AND trim(ESCH_EMPCODE) = :empcode\r\n" + "       AND trim(CSPK_COY) = :coy\r\n"
			+ "       AND :paymonth BETWEEN To_char(CSPK_EFFECTIVEFROM, 'YYYYMM') AND To_char(CSPK_EFFECTIVEUPTO, 'YYYYMM')\r\n"
			+ "       AND :paymonth BETWEEN To_char(ESCH_ENTRYDATE, 'YYYYMM') AND To_char(ESCH_SCHEMEENDDATE, 'YYYYMM')\r\n"
			+ "UNION\r\n" + "SELECT ELOAN_EMPCODE as Empcode,\r\n" + "       CSPK_EARNDEDCODE as Earndedcode,\r\n"
			+ "       EDHM_EARNDEDTYPE as Earndedtype,\r\n" + "       EDHM_COMPUTENO as Computeno,\r\n"
			+ "       EDHM_COMPUTETYPE as Computetype,\r\n" + "       EDHM_SCHEMEYN as Schemeyn,\r\n"
			+ "       EDHM_LOANYN as Loanyn,\r\n" + "       EDHM_DEFAULTSALTYPE as Defaultsaltype,\r\n"
			+ "       0 as Earndedrate,\r\n" + "       CSPK_PAYCYCLE as Paycycle,\r\n"
			+ "       CSPK_RATECYCLE as Ratecycle,\r\n" + "       'Y' AS Schemeapplyn\r\n" + "FROM   EARNDEDMASTER,\r\n"
			+ "       COYSALARYPACKAGE,\r\n" + "       EMPLOANINFO\r\n"
			+ "WHERE  Rtrim(CSPK_EARNDEDCODE) = Rtrim(EDHM_EARNDEDCODE)\r\n"
			+ "       AND Rtrim(CSPK_EARNDEDCODE) = Rtrim(ELOAN_LOANCODE)\r\n" + "       AND EDHM_LOANYN = 'Y'\r\n"
			+ "       AND EDHM_SCHEMEYN = 'N'\r\n" + "       AND trim(ELOAN_EMPCODE) = :empcode\r\n"
			+ "       AND trim(CSPK_COY) = :coy\r\n"
			+ "       AND :paymonth BETWEEN To_char(CSPK_EFFECTIVEFROM, 'YYYYMM') AND To_char(CSPK_EFFECTIVEUPTO, 'YYYYMM')\r\n"
			+ "\r\n" + ")\r\n" + "ORDER  BY Computeno", nativeQuery = true)
	List<Tuple> findByGetPackage(String coy, String paymonth, String empcode);

	@Query("SELECT new kraheja.payroll.bean.response.GetInputScreenBean(c.cmstEarndedcode                                          AS Earndedcode,\r\n"
			+ "       c.coymthsaltypesCK.cmstSalarytype                          AS Salarytype,\r\n"
			+ "       c.coymthsaltypesCK.cmstCoy                                 AS Coy,\r\n"
			+ "       c.coymthsaltypesCK.cmstPaymonth                            AS Paymonth,\r\n"
			+ "       c.cmstYrsalrevno                                           AS YrsalRevNo,\r\n"
			+ "       c.cmstMthsalrevno                                          AS MthsalRevNo,\r\n"
			+ "       Nvl(To_char(c.cmstCurrbonusdt, 'dd/mm/yyyy'), '01/01/1900') AS CurrBonusDate,\r\n"
			+ "       Nvl(To_char(c.cmstLastbonusdt, 'dd/mm/yyyy'), '01/01/1900') AS LastBonusDate,\r\n"
			+ "       Nvl(c.cmstBonuspaidyn, ' ')                                 AS BonusPaid,\r\n"
			+ "       Nvl(c.cmstBonusperiodyn, ' ')                               AS BonusPeriod,\r\n"
			+ "       Nvl(c.cmstYrstartmonth, ' ')                                AS YearStartMonth,\r\n"
			+ "       Nvl(c.cmstYrendmonth, ' ')                                  AS YearEndMonth,\r\n"
			+ "       Nvl(c.cmstItdefermth, ' ')                                  AS ItDedDiffMth,\r\n"
			+ "       Nvl(c.cmstItnextmth, ' ')                                   AS ItDedNextMth,\r\n"
			+ "       (SELECT entName\r\n" + "        FROM   DbEntity\r\n"
			+ "        WHERE  entityCk.entClass = 'PAYRL'\r\n" + "               AND entityCk.entId = 'SALTP'\r\n"
			+ "               AND entityCk.entChar1 = c.coymthsaltypesCK.cmstSalarytype)                   AS SalaryTyName,\r\n"
			+ "       (SELECT COUNT(d.emppaymonthCK.empmEmpcode)\r\n" + "        FROM   Emppaymonth d\r\n"
			+ "        WHERE  d.emppaymonthCK.empmPaymonth = ( c.coymthsaltypesCK.cmstPaymonth )\r\n"
			+ "               AND d.emppaymonthCK.empmSalarytype = c.coymthsaltypesCK.cmstSalarytype\r\n"
			+ "               AND ( 'ALL' IN ( :empcode )\r\n"
			+ "                      OR trim(d.emppaymonthCK.empmEmpcode) IN ( :empcode ) )\r\n"
			+ "               AND d.emppaymonthCK.empmEmpcode IN (SELECT DISTINCT g.empjobinfoCK.ejinEmpcode\r\n"
			+ "                                    FROM   Empjobinfo g\r\n"
			+ "                                    WHERE  g.ejinCompany = c.coymthsaltypesCK.cmstCoy\r\n"
			+ "                                           AND ( 'ALL' IN ( :emptype )\r\n"
			+ "                                                  OR trim(g.ejinEmptype) IN ( :emptype ) ))\r\n"
			+ "               AND d.empmPaystatus = 'H')                          AS onhold,\r\n"
			+ "       (SELECT COUNT(e.emppaymonthCK.empmEmpcode)\r\n" + "        FROM   Emppaymonth e\r\n"
			+ "        WHERE  e.emppaymonthCK.empmPaymonth = ( CASE\r\n"
			+ "                                   WHEN ( (SELECT h.ejinJobstatus\r\n"
			+ "                                           FROM   Empjobinfo h\r\n"
			+ "                                           WHERE  h.empjobinfoCK.ejinEmpcode = e.emppaymonthCK.empmEmpcode\r\n"
			+ "                                                  AND h.ejinEffectiveupto = '01-JAN-2050'\r\n"
			+ "                                                  AND trim(h.ejinCompany) IN  :coy ) = 'T' ) THEN (SELECT To_char(i.ejinSettlementdate, 'yyyymm')\r\n"
			+ "                                                                                                FROM   Empjobinfo i\r\n"
			+ "                                                                                                WHERE  i.empjobinfoCK.ejinEmpcode = e.emppaymonthCK.empmEmpcode\r\n"
			+ "                                                                                                       AND i.ejinEffectiveupto = '01-JAN-2050'\r\n"
			+ "                                                                                                       AND trim(i.ejinCompany) IN  :coy )\r\n"
			+ "                                   ELSE c.coymthsaltypesCK.cmstPaymonth\r\n"
			+ "                                 END )\r\n"
			+ "               AND e.emppaymonthCK.empmSalarytype = c.coymthsaltypesCK.cmstSalarytype\r\n"
			+ "               AND ( 'ALL' IN ( :empcode )\r\n"
			+ "                      OR trim(e.emppaymonthCK.empmEmpcode) IN ( :empcode ) )\r\n"
			+ "               AND e.emppaymonthCK.empmEmpcode IN (SELECT DISTINCT j.empjobinfoCK.ejinEmpcode\r\n"
			+ "                                    FROM   Empjobinfo j\r\n"
			+ "                                    WHERE  j.ejinCompany = c.coymthsaltypesCK.cmstCoy\r\n"
			+ "                                           AND ( 'ALL' IN ( :emptype )\r\n"
			+ "                                                  OR trim(j.ejinEmptype) IN ( :emptype ) ))\r\n"
			+ "               AND e.empmPaystatus = 'L')                          AS freshcompute,\r\n"
			+ "       (SELECT COUNT(f.emppaymonthCK.empmEmpcode)\r\n" + "        FROM   Emppaymonth f\r\n"
			+ "        WHERE  f.emppaymonthCK.empmPaymonth = ( c.coymthsaltypesCK.cmstPaymonth )\r\n"
			+ "               AND f.emppaymonthCK.empmSalarytype = c.coymthsaltypesCK.cmstSalarytype\r\n"
			+ "               AND ( 'ALL' IN ( :empcode )\r\n"
			+ "                      OR trim(f.emppaymonthCK.empmEmpcode) IN ( :empcode ) )\r\n"
			+ "               AND f.emppaymonthCK.empmEmpcode IN (SELECT DISTINCT k.empjobinfoCK.ejinEmpcode\r\n"
			+ "                                    FROM   Empjobinfo k\r\n"
			+ "                                    WHERE  k.ejinCompany = c.coymthsaltypesCK.cmstCoy\r\n"
			+ "                                           AND ( 'ALL' IN ( :emptype )\r\n"
			+ "                                                  OR trim(k.ejinEmptype) IN ( :emptype ) ))\r\n"
			+ "               AND f.empmPaystatus = 'P')                          AS recompute)\r\n"
			+ "FROM   Coymthsaltypes c\r\n" + "WHERE  trim(c.coymthsaltypesCK.cmstCoy) IN  :coy \r\n"
			+ "       AND trim(c.coymthsaltypesCK.cmstSalarytype) IN ( :saltype )")
	List<GetInputScreenBean> findByInputScreen(Set<String> coy, String empcode, String emptype, String saltype);

	@Query("SELECT new kraheja.payroll.bean.response.GetInputScreenBean(c.cmstEarndedcode                                          AS Earndedcode,\r\n"
			+ "       c.coymthsaltypesCK.cmstSalarytype                          AS Salarytype,\r\n"
			+ "       c.coymthsaltypesCK.cmstCoy                                 AS Coy,\r\n" + "       ( CASE\r\n"
			+ "           WHEN ( (SELECT DISTINCT l.ejinJobstatus\r\n" + "                   FROM   Empjobinfo l\r\n"
			+ "                   WHERE  trim(l.empjobinfoCK.ejinEmpcode) IN ( :empcode )\r\n"
			+ "                          AND trim(l.ejinCompany) IN ( :coy )\r\n"
			+ "                          AND l.ejinEffectiveupto = '01-JAN-2050') = 'T' ) THEN (SELECT To_char(m.ejinSettlementdate, 'yyyymm')\r\n"
			+ "                                                                                FROM   Empjobinfo m\r\n"
			+ "                                                                                WHERE  trim(m.empjobinfoCK.ejinEmpcode) IN ( :empcode )\r\n"
			+ "                                                                                       AND trim(m.ejinCompany) IN ( :coy )\r\n"
			+ "                                                                                       AND m.ejinEffectiveupto = '01-JAN-2050')\r\n"
			+ "           ELSE c.coymthsaltypesCK.cmstPaymonth\r\n"
			+ "         END )                                                    AS Paymonth,"
			+ "       c.cmstYrsalrevno                                           AS YrsalRevNo,\r\n"
			+ "       c.cmstMthsalrevno                                          AS MthsalRevNo,\r\n"
			+ "       Nvl(To_char(c.cmstCurrbonusdt, 'dd/mm/yyyy'), '01/01/1900') AS CurrBonusDate,\r\n"
			+ "       Nvl(To_char(c.cmstLastbonusdt, 'dd/mm/yyyy'), '01/01/1900') AS LastBonusDate,\r\n"
			+ "       Nvl(c.cmstBonuspaidyn, ' ')                                 AS BonusPaid,\r\n"
			+ "       Nvl(c.cmstBonusperiodyn, ' ')                               AS BonusPeriod,\r\n"
			+ "       Nvl(c.cmstYrstartmonth, ' ')                                AS YearStartMonth,\r\n"
			+ "       Nvl(c.cmstYrendmonth, ' ')                                  AS YearEndMonth,\r\n"
			+ "       Nvl(c.cmstItdefermth, ' ')                                  AS ItDedDiffMth,\r\n"
			+ "       Nvl(c.cmstItnextmth, ' ')                                   AS ItDedNextMth,\r\n"
			+ "       (SELECT entName\r\n" + "        FROM   DbEntity\r\n"
			+ "        WHERE  entityCk.entClass = 'PAYRL'\r\n" + "               AND entityCk.entId = 'SALTP'\r\n"
			+ "               AND entityCk.entChar1 = c.coymthsaltypesCK.cmstSalarytype)                   AS SalaryTyName,\r\n"
			+ "       (SELECT COUNT(d.emppaymonthCK.empmEmpcode)\r\n" + "        FROM   Emppaymonth d\r\n"
			+ "        WHERE  d.emppaymonthCK.empmPaymonth = ( ( CASE \r\n"
			+ "			           WHEN ( (SELECT DISTINCT n.ejinJobstatus\r\n"
			+ "			                   FROM   Empjobinfo n\r\n"
			+ "			                   WHERE  trim(n.empjobinfoCK.ejinEmpcode) IN ( :empcode )\r\n"
			+ "			                          AND trim(n.ejinCompany) IN ( :coy )\r\n"
			+ "			                          AND n.ejinEffectiveupto = '01-JAN-2050') = 'T' ) THEN (SELECT To_char(o.ejinSettlementdate, 'yyyymm')\r\n"
			+ "			                                                                                FROM   Empjobinfo o\r\n"
			+ "			                                                                                WHERE  trim(o.empjobinfoCK.ejinEmpcode) IN ( :empcode )\r\n"
			+ "			                                                                                       AND trim(o.ejinCompany) IN ( :coy )\r\n"
			+ "			                                                                                       AND o.ejinEffectiveupto = '01-JAN-2050')\r\n"
			+ "			           ELSE c.coymthsaltypesCK.cmstPaymonth\r\n" + "			         END ) )\r\n"
			+ "               AND d.emppaymonthCK.empmSalarytype = c.coymthsaltypesCK.cmstSalarytype\r\n"
			+ "               AND ( 'ALL' IN ( :empcode )\r\n"
			+ "                      OR trim(d.emppaymonthCK.empmEmpcode) IN ( :empcode ) )\r\n"
			+ "               AND d.emppaymonthCK.empmEmpcode IN (SELECT DISTINCT g.empjobinfoCK.ejinEmpcode\r\n"
			+ "                                    FROM   Empjobinfo g\r\n"
			+ "                                    WHERE  g.ejinCompany = c.coymthsaltypesCK.cmstCoy\r\n"
			+ "                                           AND ( 'ALL' IN ( :emptype )\r\n"
			+ "                                                  OR trim(g.ejinEmptype) IN ( :emptype ) ))\r\n"
			+ "               AND d.empmPaystatus = 'H')                          AS onhold,\r\n"
			+ "       (SELECT COUNT(e.emppaymonthCK.empmEmpcode)\r\n" + "        FROM   Emppaymonth e\r\n"
			+ "        WHERE  e.emppaymonthCK.empmPaymonth = ( CASE\r\n"
			+ "                                   WHEN ( (SELECT h.ejinJobstatus\r\n"
			+ "                                           FROM   Empjobinfo h\r\n"
			+ "                                           WHERE  h.empjobinfoCK.ejinEmpcode = e.emppaymonthCK.empmEmpcode\r\n"
			+ "                                                  AND h.ejinEffectiveupto = '01-JAN-2050'\r\n"
			+ "                                                  AND trim(h.ejinCompany) IN ( :coy )) = 'T' ) THEN (SELECT To_char(i.ejinSettlementdate, 'yyyymm')\r\n"
			+ "                                                                                                FROM   Empjobinfo i\r\n"
			+ "                                                                                                WHERE  i.empjobinfoCK.ejinEmpcode = e.emppaymonthCK.empmEmpcode\r\n"
			+ "                                                                                                       AND i.ejinEffectiveupto = '01-JAN-2050'\r\n"
			+ "                                                                                                       AND trim(i.ejinCompany) IN ( :coy ))\r\n"
			+ "                                   ELSE c.coymthsaltypesCK.cmstPaymonth\r\n"
			+ "                                 END )\r\n"
			+ "               AND e.emppaymonthCK.empmSalarytype = c.coymthsaltypesCK.cmstSalarytype\r\n"
			+ "               AND ( 'ALL' IN ( :empcode )\r\n"
			+ "                      OR trim(e.emppaymonthCK.empmEmpcode) IN ( :empcode ) )\r\n"
			+ "               AND e.emppaymonthCK.empmEmpcode IN (SELECT DISTINCT j.empjobinfoCK.ejinEmpcode\r\n"
			+ "                                    FROM   Empjobinfo j\r\n"
			+ "                                    WHERE  j.ejinCompany = c.coymthsaltypesCK.cmstCoy\r\n"
			+ "                                           AND ( 'ALL' IN ( :emptype )\r\n"
			+ "                                                  OR trim(j.ejinEmptype) IN ( :emptype ) ))\r\n"
			+ "               AND e.empmPaystatus = 'L')                          AS freshcompute,\r\n"
			+ "       (SELECT COUNT(f.emppaymonthCK.empmEmpcode)\r\n" + "        FROM   Emppaymonth f\r\n"
			+ "        WHERE  f.emppaymonthCK.empmPaymonth = ( ( CASE \r\n"
			+ "			           WHEN ( (SELECT DISTINCT p.ejinJobstatus\r\n"
			+ "			                   FROM   Empjobinfo p\r\n"
			+ "			                   WHERE  trim(p.empjobinfoCK.ejinEmpcode) IN ( :empcode )\r\n"
			+ "			                          AND trim(p.ejinCompany) IN ( :coy )\r\n"
			+ "			                          AND p.ejinEffectiveupto = '01-JAN-2050') = 'T' ) THEN (SELECT To_char(q.ejinSettlementdate, 'yyyymm')\r\n"
			+ "			                                                                                FROM   Empjobinfo q\r\n"
			+ "			                                                                                WHERE  trim(q.empjobinfoCK.ejinEmpcode) IN ( :empcode )\r\n"
			+ "			                                                                                       AND trim(q.ejinCompany) IN ( :coy )\r\n"
			+ "			                                                                                       AND q.ejinEffectiveupto = '01-JAN-2050')\r\n"
			+ "			           ELSE c.coymthsaltypesCK.cmstPaymonth\r\n" + "			         END ) )\r\n"
			+ "               AND f.emppaymonthCK.empmSalarytype = c.coymthsaltypesCK.cmstSalarytype\r\n"
			+ "               AND ( 'ALL' IN ( :empcode )\r\n"
			+ "                      OR trim(f.emppaymonthCK.empmEmpcode) IN ( :empcode ) )\r\n"
			+ "               AND f.emppaymonthCK.empmEmpcode IN (SELECT DISTINCT k.empjobinfoCK.ejinEmpcode\r\n"
			+ "                                    FROM   Empjobinfo k\r\n"
			+ "                                    WHERE  k.ejinCompany = c.coymthsaltypesCK.cmstCoy\r\n"
			+ "                                           AND ( 'ALL' IN ( :emptype )\r\n"
			+ "                                                  OR trim(k.ejinEmptype) IN ( :emptype ) ))\r\n"
			+ "               AND f.empmPaystatus = 'P')                          AS recompute)\r\n"
			+ "FROM   Coymthsaltypes c\r\n" + "WHERE  trim(c.coymthsaltypesCK.cmstCoy) IN ( :coy )\r\n"
			+ "       AND trim(c.coymthsaltypesCK.cmstSalarytype) IN ( :saltype )")
	List<GetInputScreenBean> findByInputScreenForProj(String coy, String empcode, String emptype, String saltype);

}
